@startuml Classes
        class User {
            {field} id: int
            {field} pseudo: string
            {field} email: string
            {field} password: string
            {field} create_at: DateTimeInterface
        }

        class Admin 

        class Category {
            {field} id: int
            {field} name: string
            {field} slug: string
        }
        
        class Trick {
            {field} id: int
            {field} name: string
            {field} slug: string
            {field} description: string
            {field} publishedAt: DateTimeInterface
        }

        class Image {
            {field} id: int
            {field} title: string
            {field} path: string
        }

        class Video {
            {field} id: int
            {field} title: string
            {field} path: string
        }

        class Comment {
            {field} id: int
            {field} publishedAt: DateTimeInterface
            {field} comment: string
        }

        User <|-- Admin : Extension

        User "1" *-- "1" Image : composition
        User "1" -- "0..*" Trick

        Category "1" o-- "0..*" Trick : aggregation
        Trick "1" *-- "1..*" Image : composition
        Trick "1" *-- "0..*" Video : composition
        Trick "1" *-- "0..*" Comment : composition
@enduml